# Override these settings with your own
title = "David Peicho's Blog"
languageCode = "en-us"
baseURL = "https://davidpeicho.github.io/"
copyright = "Â© {year}"

# Optional params
[params]
  # Follow the Hugo date/time format reference here:
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2006"

  description = "David Peicho's blog about computer graphics, rendering, game developmnent, or just computer science!"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  twitter = "https://twitter.com/DavidPeicho"
  github = "https://github.com/DavidPeicho"
  # email = "mailto:<your email>"
  linkedin = "https://www.linkedin.com/in/david-peicho/"
  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported:
  #   "Twitter", "GitHub", "Email", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconTitles = [ "Twitter", "GitHub" ]

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false

  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation

[[menu.main]]
  identifier = "home"
  name = "home"
  title = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/about"
  weight = 2

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"
  weight = 3

[[menu.main]]
  identifier = "teaching"
  name = "teaching"
  title = "Teaching"
  url = "/teaching"
  weight = 4
